version: 2.4

jobs:
  build:
    docker:
      - image: node:19.6.0
    environment:
      repo_token: lLqKyNNKIgzBau6H5YKe4sS1SgXnA1BKa
      DATABASE: $CIRCLECI_DATABASE
      JWT_SECRET: $CIRCLECI_JWT_SECRET
      JWT_EXPIRES_IN: $CIRCLECI_JWT_EXPIRES_IN
      JWT_COOKIE_EXPIRES_IN: $CIRCLECI_JWT_COOKIE_EXPIRES_IN
      CLOUDINARY_CLOUD_NAME: $CIRCLECI_CLOUDINARY_CLOUD_NAME
      CLOUDINARY_API_KEY: $CIRCLECI_CLOUDINARY_API_KEY
      CLOUDINARY_API_SECRET: $CIRCLECI_CLOUDINARY_API_SECRET

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run tests
          command: npm test --coverage

      - run:
          name: Upload coverage to Coveralls
          command: npx coveralls < coverage/lcov.info
